// use this converter to create your own template : http://www.accessify.com/tools-and-wizards/developer-tools/html-javascript-convertor/

var template="";
template += "<!-- Root element of PhotoSwipe. Must have class pswp. -->";
template += "<div class=\"pswp\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">";
template += "";
template += "    <!-- Background of PhotoSwipe. ";
template += "         It's a separate element as animating opacity is faster than rgba(). -->";
template += "    <div class=\"pswp__bg\"><\/div>";
template += "";
template += "    <!-- Slides wrapper with overflow:hidden. -->";
template += "    <div class=\"pswp__scroll-wrap\">";
template += "";
template += "        <!-- Container that holds slides. ";
template += "            PhotoSwipe keeps only 3 of them in the DOM to save memory.";
template += "            Don't modify these 3 pswp__item elements, data is added later on. -->";
template += "        <div class=\"pswp__container\">";
template += "            <div class=\"pswp__item\"><\/div>";
template += "            <div class=\"pswp__item\"><\/div>";
template += "            <div class=\"pswp__item\"><\/div>";
template += "        <\/div>";
template += "";
template += "        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->";
template += "        <div class=\"pswp__ui pswp__ui--hidden\">";
template += "";
template += "            <div class=\"pswp__top-bar\">";
template += "";
template += "                <!--  Controls are self-explanatory. Order can be changed. -->";
template += "";
template += "                <div class=\"pswp__counter\"><\/div>";
template += "";
template += "                <button class=\"pswp__button pswp__button--close\" title=\"Close (Esc)\"><\/button>";
template += "";
template += "                <button class=\"pswp__button pswp__button--share\" title=\"Share\"><\/button>";
template += "";
template += "                <button class=\"pswp__button pswp__button--fs\" title=\"Toggle fullscreen\"><\/button>";
template += "";
template += "                <button class=\"pswp__button pswp__button--zoom\" title=\"Zoom in\/out\"><\/button>";
template += "";
template += "                <!-- Preloader demo http:\/\/codepen.io\/dimsemenov\/pen\/yyBWoR -->";
template += "                <!-- element will get class pswp__preloader--active when preloader is running -->";
template += "                <div class=\"pswp__preloader\">";
template += "                    <div class=\"pswp__preloader__icn\">";
template += "                      <div class=\"pswp__preloader__cut\">";
template += "                        <div class=\"pswp__preloader__donut\"><\/div>";
template += "                      <\/div>";
template += "                    <\/div>";
template += "                <\/div>";
template += "            <\/div>";
template += "";
template += "            <div class=\"pswp__share-modal pswp__share-modal--hidden pswp__single-tap\">";
template += "                <div class=\"pswp__share-tooltip\"><\/div> ";
template += "            <\/div>";
template += "";
template += "            <button class=\"pswp__button pswp__button--arrow--left\" title=\"Previous (arrow left)\">";
template += "            <\/button>";
template += "";
template += "            <button class=\"pswp__button pswp__button--arrow--right\" title=\"Next (arrow right)\">";
template += "            <\/button>";
template += "";
template += "            <div class=\"pswp__caption\">";
template += "                <div class=\"pswp__caption__center\"><\/div>";
template += "            <\/div>";
template += "";
template += "        <\/div>";
template += "";
template += "    <\/div>";
template += "";
template += "<\/div>";

export { template };